### ISSUE TITLE
validate db version query error

### ISSUE THREAD

**Issue by tatsu-i** [storj/storj#3790]
An error occurs during database version check.

```
satellite_1      | 2020-03-01T07:32:00.588Z	INFO	process/exec_conf.go:269	Configuration loaded from: /root/.local/share/storj/satellite/config.yaml
satellite_1      | 2020-03-01T07:32:00.677Z	DEBUG	db	satellitedb/database.go:79	Connected to:	{"db source": "postgres://postgres:postgres@postgres/satellite?sslmode=disable&application_name=Satellite"}
satellite_1      | 2020-03-01T07:32:00.694Z	DEBUG	pointerdb	metainfo/config.go:94	Connected to:	{"db source": "postgres://postgres:postgres@postgres/satellite?sslmode=disable"}
satellite_1      | 2020-03-01T07:32:00.706Z	DEBUG	satellite/core.go:178	Binary Version: v0.0.0 with CommitHash df88f416c9a07c6d94dc81ad6f173da7b1ccd2f7-dirty, built at 2020-02-28 14:03:41 +0000 UTC as Release false
satellite_1      | 2020-03-01T07:32:00.706Z	DEBUG	satellite/core.go:190	Starting listener and server
satellite_1      | 2020-03-01T07:32:00.708Z	INFO	telemetry	process/metrics.go:56	disabled
satellite_1      | 2020-03-01T07:32:00.710Z	FATAL	satellite/main.go:259	failed satellite database version check: validate db version query error: migrate: pq: Could not complete operation in a failed transaction
satellite_1      | main.cmdRun
satellite_1      | 	/go/src/storj.io/storj/cmd/satellite/main.go:259
satellite_1      | storj.io/storj/pkg/process.cleanup.func1.2
satellite_1      | 	/go/src/storj.io/storj/pkg/process/exec_conf.go:312
satellite_1      | storj.io/storj/pkg/process.cleanup.func1
satellite_1      | 	/go/src/storj.io/storj/pkg/process/exec_conf.go:330
satellite_1      | github.com/spf13/cobra.(*Command).execute
satellite_1      | 	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
satellite_1      | github.com/spf13/cobra.(*Command).ExecuteC
satellite_1      | 	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
satellite_1      | github.com/spf13/cobra.(*Command).Execute
satellite_1      | 	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
satellite_1      | storj.io/storj/pkg/process.ExecWithCustomConfig
satellite_1      | 	/go/src/storj.io/storj/pkg/process/exec_conf.go:84
satellite_1      | storj.io/storj/pkg/process.ExecCustomDebug
satellite_1      | 	/go/src/storj.io/storj/pkg/process/exec_conf.go:66
satellite_1      | main.main
satellite_1      | 	/go/src/storj.io/storj/cmd/satellite/main.go:455
satellite_1      | runtime.main
satellite_1      | 	/usr/local/go/src/runtime/proc.go:203

```
docker-compose.yaml
```
version: '3.4'
services:
  redis:
    image: redis
  postgres:
    image: postgres:9.6
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_DB=satellite

  satellite:
    image: storjlabs/satellite:${VERSION:-latest}
    environment:
    - API_KEY=abc123
    - STORJ_CHECKER_QUEUE_ADDRESS=redis://redis:6379/?db=0
    - STORJ_DATABASE=postgres://postgres:postgres@postgres/satellite?sslmode=disable
    - STORJ_LOG_LEVEL=debug
    - STORJ_REPAIRER_QUEUE_ADDRESS=redis://redis:6379/?db=0
    - STORJ_IDENTITY_SERVER_ADDRESS=satellite:7777
    volumes:
     - ./identity/satellite-1/storagenode/:/root/.local/share/storj/identity/satellite/
     - /data/storj/satellite-1:/root/.local/share/storj/satellite/
    restart: always
    ports:
     - 7778:7777
    links:
     - redis
     - postgres
    depends_on:
     - redis
     - postgres

```

/data/storj/satellite-1/config.yaml
```
console.address: 0.0.0.0:10100
console.static-dir: /app
contact.external-address: ""
database: postgres://postgres:postgres@postgres/satellite?sslmode=disable
identity.cert-path: /root/.local/share/storj/identity/satellite/identity.cert
identity.key-path: /root/.local/share/storj/identity/satellite/identity.key
live-accounting.storage-backend: redis://redis:6379?db=1
metainfo.database-url: postgres://postgres:postgres@postgres/satellite?sslmode=disable
server.address: :7777
server.debug-log-traffic: false
server.private-address: 127.0.0.1:7778
server.revocation-dburl: redis://redis:6379?db=2

```
