### ISSUE TITLE
It would be nice if the IP Address was detected.

### ISSUE THREAD

**Issue by sixcorners** [storj/storj#3923]
It would be nice if I didn't have to have a different configuration per node to set the advertised IP address or set the entrypoint/command to look up that information. It's good to be able to set it manually but usually the IP the node contacted the satellite with is the correct IP to use. If the IP turns out to be something that changes the software would be in the best position to fix it when it does.

**Comment by stefanbenten** [comment]
Hey @sixcorners ,

I do not see where the issue/advantage is. We should not try to make an IP updater in our software (that’s not the expertise and purpose of it).
An good example is the actual DDNS address that we recommend to add/use. Furthermore the port of a node has to change anyway, if ran within the same network as others (behind your firewall/router). For that reason, I do not believe that striping this out and trying to automatically do this, is a good idea.

**Comment by sixcorners** [comment]
If you manage multiple machines with different IP addresses then the port doesn't have to change. I think it's actually recommended to not run multiple nodes behind the same IP since they get treated as the same node for purposes of selecting a node to upload a file to and for auditing.
Anyway, if this was implemented it would allow me to have one config for a cluster of servers. I don't know what that is worth.

**Comment by stefanbenten** [comment]
You might want to use Environment variables in this case. That would serve your needs.
Lemme know if you need help with that!

**Comment by sixcorners** [comment]
Ok environment variables...
```
version: "3.7"
services:
  storjnode:
    image: storjlabs/storagenode:beta
    restart: unless-stopped
    deploy:
      mode: global
      stop_grace_period: 5m
    environment:
      - WALLET=0xxxxxx
      - EMAIL=xxxxx
      - ADDRESS=${HOST_IPV4}:28967
      - STORAGE=500GB
    volumes:
      - storj-identity:/app/identity
      - storj-storage:/app/config
    ports:
      - 28967:28967
volumes:
  storj-identity:
  storj-storage:
```
I deployed this on my swarm cluster. Now I have 3 storj nodes that are all reporting the same ip address. What do I do now?
