### ISSUE TITLE
[DOC] Document how to enable zkSync in Docker deployments

### ISSUE THREAD

**Issue by mark-stopka** [storj/storj#4067]
Hi,
it would be great to have an easy way to enable zkSync in Docker deployments, but I've noticed it's not one of exported varibales in your `entrypoint` script.

**Comment by mark-stopka** [comment]
Hello, no update on this?

**Comment by AlexeyALeonov** [comment]
https://github.com/storj/storj/wiki/zksync#docker-versions

**Comment by dominickmarino** [comment]
Quoted from the link above 

If you use a docker version, you can also specify the zksync wallet feature as an option after the image name, for example:

```
docker run ... storjlabs/storagenode:latest --operator.wallet-features=zksync
```
Please enter everything in lowercase and double-check for spelling mistakes. This is a very basic implementation without any validations.



If you decided to specify the zksync wallet feature as an option, you need to stop and remove the container and run it back with all your parameters include added option for wallet feature, otherwise you can just restart the container.

**Comment by mark-stopka** [comment]
@dominickmarino missed this update, sorry :-(

**Comment by mark-stopka** [comment]
https://forum.storj.io/t/jan-14-2022-payouts-for-the-month-of-december-are-now-complete-and-polygon-announcement/16814

**Comment by mark-stopka** [comment]
Example Docker Swarm config:

```yaml
[root@docker-host-01 storj]# cat docker-stack.yaml 
version: '3.7'

services:
  node:
    image: storjlabs/storagenode:beta
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - storj-id:/app/identity
      - /mnt/storj/:/app/config
    environment:
      - TZ=Europe/Prague
      - WALLET=<wallet address>
      - EMAIL=<email address>
      - ADDRESS=<server fqdn>:28967
      - STORAGE=3.9TB
    command: --operator.wallet-features=zksync
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_backend
      - traefik.http.routers.storj_A01.rule=Host(`<web interface URL>`)
      - traefik.http.routers.storj_A01.entrypoints=http,https
      - traefik.http.services.myservice.loadbalancer.server.port=14002
    ports:
      - target: 28967
        published: 28967
        protocol: tcp
        mode: host
      - target: 28967
        published: 28967
        protocol: udp
        mode: host
    networks:
      - default
      - traefik_backend

networks:
  traefik_backend:
    external:
      name: traefik_backend

volumes:
  storj-id:
  storj-id-a02:
[root@docker-host-01 storj]# 
```

![image](https://user-images.githubusercontent.com/18139116/152596965-27fc9bc1-b30e-4d64-99f8-1213fd5705f9.png)
