### ISSUE TITLE
Release-v1.50 Test Multinode Dashboard Docker Image

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#4589]
https://github.com/storj/storj/blob/main/cmd/multinode/README.md

**Comment by littleskunk** [comment]
```
version: "3.3"
services:
  multinode:
    restart: unless-stopped
    user: 1000:1000
    image: storjlabs/multinode:latest
    ports:
      - 15002:15002/tcp
    volumes:
      - /home/storagenode/.local/share/storj/identity/multinode:/app/identity
      - /home/storagenode/.local/share/storj/multinode:/app/config
```
