### ISSUE TITLE
Testing Segment placement

### ISSUE THREAD

**Issue by ihaid** [storj/storj#6698]
Node Selection:
	Test declumping soc2 data in storj-up
	Test S3 call to get bucket placement with location setting and the new name setting
	931efa0 satellite/nodeselection: extend Placement with Selector
	b41cf66 satellite/{nodeselection,repair}: Placement level invariant for customizable declumping
	17a1628 satellite/nodeselection: introduce Name for Placement

**Comment by ihaid** [comment]
What was tested:

- new code and old placement settings:
-- 	queue up segments for repair
-- 	repair checker deleting elements from the repair queue
-- 	download segments from nodes even when all pieces are violating the placement constrain (checking that placement violations are not treated like disqualified nodes)
--	upload new pieces to the right nodes
--	repair worker include/exclude settings to ignore repair tasks that have the wrong placement setting
	

- new code and new placement settings
	-- queue up segments for repair
	-- repair checker deleting elements from the repair queue
	-- download segments from nodes even when all pieces are violating the placement constrain (checking that placement violations are not treated like disqualified nodes)
	-- upload new pieces to the right nodes
	-- repair worker include/exclude settings to ignore repair tasks that have the wrong placement setting
	
- extra tests:
		-- set `invariant: maxcontrol("email",2)` and have 3 nodes with the same email. Some of the uploads are stored on 3 nodes with same email address. -> repair check needs to queue up and repair worker need to find a new node.
		-- simulate repair loop in an imbalanced network with 8 nodes sharing the same email address.

**Comment by ihaid** [comment]
For these tests placement.yaml file looks like:
```
templates:
  SIGNER_ZERO: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4
  NORMAL: exclude(tag("$SIGNER_ZERO","selected","true"))
placements:
  - id: 0
    name: global
    filter: $NORMAL
    invariant: maxcontrol("last_net",5)
  - id: 10
    name: soc2
    filter: tag("$SIGNER_ZERO","selected","true")
    invariant: maxcontrol("email",2)
    selector: random()
```
